services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hotel-database-sqlserver
    ports:
      - "${MSSQL_PORT}:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_PID: "${MSSQL_PID}"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./sql:/sql
      - ./backups:/backups
    restart: unless-stopped

volumes:
  sqlserver_data:
