USE HotelDatabase;
GO

SET NOCOUNT ON;
GO

ALTER TABLE dbo.CLIENT ADD CONSTRAINT UQ_CLIENT_email_hash UNIQUE (email_hash);
ALTER TABLE dbo.CLIENT ADD CONSTRAINT CK_CLIENT_names_not_blank CHECK (LEN(LTRIM(RTRIM(first_name))) > 0 AND LEN(LTRIM(RTRIM(last_name))) > 0);
ALTER TABLE dbo.CLIENT ADD CONSTRAINT CK_CLIENT_encrypted_lengths CHECK (DATALENGTH(email_encrypted) >= 32 AND (phone_number_encrypted IS NULL OR DATALENGTH(phone_number_encrypted) >= 32));

ALTER TABLE dbo.ROLES ADD CONSTRAINT UQ_ROLES_rol_name UNIQUE (rol_name);

ALTER TABLE dbo.USERS ADD CONSTRAINT UQ_USERS_username UNIQUE (username);
ALTER TABLE dbo.USERS ADD CONSTRAINT UQ_USERS_email UNIQUE (email);
ALTER TABLE dbo.USERS ADD CONSTRAINT CK_USERS_password_hash_length CHECK (DATALENGTH(password_hash) = 32 AND DATALENGTH(salt) = 16);
ALTER TABLE dbo.USERS ADD CONSTRAINT FK_USERS_ROLES FOREIGN KEY (role_id) REFERENCES dbo.ROLES(role_id);

ALTER TABLE dbo.RESERVATION_STATES ADD CONSTRAINT UQ_RESERVATION_STATES_name UNIQUE (reservation_state_name);
ALTER TABLE dbo.RESERVATIONS ADD CONSTRAINT CK_RESERVATIONS_dates CHECK (check_out_date > check_in_date);
ALTER TABLE dbo.RESERVATIONS ADD CONSTRAINT FK_RESERVATIONS_CLIENT FOREIGN KEY (client_id) REFERENCES dbo.CLIENT(client_id);
ALTER TABLE dbo.RESERVATIONS ADD CONSTRAINT FK_RESERVATIONS_RESERVATION_STATES FOREIGN KEY (reservation_state_id) REFERENCES dbo.RESERVATION_STATES(reservation_state_id);

ALTER TABLE dbo.ROOM_TYPES ADD CONSTRAINT UQ_ROOM_TYPES_name UNIQUE (name);
ALTER TABLE dbo.ROOM_TYPES ADD CONSTRAINT CK_ROOM_TYPES_values CHECK (capacity > 0 AND price >= 0);

ALTER TABLE dbo.ROOM_STATES ADD CONSTRAINT UQ_ROOM_STATES_name UNIQUE (state_name);

ALTER TABLE dbo.ROOMS ADD CONSTRAINT UQ_ROOMS_room_number UNIQUE (room_number);
ALTER TABLE dbo.ROOMS ADD CONSTRAINT CK_ROOMS_floor CHECK (room_floor >= 0);
ALTER TABLE dbo.ROOMS ADD CONSTRAINT FK_ROOMS_ROOM_TYPES FOREIGN KEY (room_type_id) REFERENCES dbo.ROOM_TYPES(room_type_id);
ALTER TABLE dbo.ROOMS ADD CONSTRAINT FK_ROOMS_ROOM_STATES FOREIGN KEY (state_id) REFERENCES dbo.ROOM_STATES(state_id);

ALTER TABLE dbo.RESERVATION_ROOMS ADD CONSTRAINT UQ_RESERVATION_ROOMS_reservation_room UNIQUE (reservation_id, room_id);
ALTER TABLE dbo.RESERVATION_ROOMS ADD CONSTRAINT FK_RESERVATION_ROOMS_RESERVATIONS FOREIGN KEY (reservation_id) REFERENCES dbo.RESERVATIONS(reservation_id);
ALTER TABLE dbo.RESERVATION_ROOMS ADD CONSTRAINT FK_RESERVATION_ROOMS_ROOMS FOREIGN KEY (room_id) REFERENCES dbo.ROOMS(room_id);

ALTER TABLE dbo.STAY_STATES ADD CONSTRAINT UQ_STAY_STATES_name UNIQUE (stay_state_name);
ALTER TABLE dbo.STAYS ADD CONSTRAINT UQ_STAYS_reservation UNIQUE (reservation_id);
ALTER TABLE dbo.STAYS ADD CONSTRAINT CK_STAYS_dates CHECK (check_out_date IS NULL OR check_out_date >= check_in_date);
ALTER TABLE dbo.STAYS ADD CONSTRAINT FK_STAYS_RESERVATIONS FOREIGN KEY (reservation_id) REFERENCES dbo.RESERVATIONS(reservation_id);
ALTER TABLE dbo.STAYS ADD CONSTRAINT FK_STAYS_USER_CHECK_IN FOREIGN KEY (user_check_in_id) REFERENCES dbo.USERS(user_id);
ALTER TABLE dbo.STAYS ADD CONSTRAINT FK_STAYS_USER_CHECK_OUT FOREIGN KEY (user_check_out_id) REFERENCES dbo.USERS(user_id);
ALTER TABLE dbo.STAYS ADD CONSTRAINT FK_STAYS_STAY_STATES FOREIGN KEY (stay_state_id) REFERENCES dbo.STAY_STATES(stay_state_id);

ALTER TABLE dbo.SERVICES ADD CONSTRAINT UQ_SERVICES_name UNIQUE (name);
ALTER TABLE dbo.SERVICES ADD CONSTRAINT CK_SERVICES_values CHECK (price >= 0 AND capacity >= 0);

ALTER TABLE dbo.RESERVATION_SERVICE_STATES ADD CONSTRAINT UQ_RESERVATION_SERVICE_STATES_name UNIQUE (reservation_service_state_name);
ALTER TABLE dbo.RESERVATION_SERVICES ADD CONSTRAINT CK_RESERVATION_SERVICES_values CHECK (quantity > 0 AND unitary_price >= 0);
ALTER TABLE dbo.RESERVATION_SERVICES ADD CONSTRAINT FK_RESERVATION_SERVICES_RESERVATIONS FOREIGN KEY (reservation_id) REFERENCES dbo.RESERVATIONS(reservation_id);
ALTER TABLE dbo.RESERVATION_SERVICES ADD CONSTRAINT FK_RESERVATION_SERVICES_SERVICES FOREIGN KEY (service_id) REFERENCES dbo.SERVICES(service_id);
ALTER TABLE dbo.RESERVATION_SERVICES ADD CONSTRAINT FK_RESERVATION_SERVICES_STATES FOREIGN KEY (reservation_service_state_id) REFERENCES dbo.RESERVATION_SERVICE_STATES(reservation_service_state_id);

ALTER TABLE dbo.CHARGE_TYPES ADD CONSTRAINT UQ_CHARGE_TYPES_name UNIQUE (name);
ALTER TABLE dbo.CHARGES ADD CONSTRAINT CK_CHARGES_values CHECK (quantity > 0 AND unitary_price >= 0 AND subtotal >= 0 AND taxes >= 0 AND total >= 0);
ALTER TABLE dbo.CHARGES ADD CONSTRAINT CK_CHARGES_single_source CHECK (reservation_room_id IS NULL OR reservation_service_id IS NULL);
ALTER TABLE dbo.CHARGES ADD CONSTRAINT FK_CHARGES_RESERVATIONS FOREIGN KEY (reservation_id) REFERENCES dbo.RESERVATIONS(reservation_id);
ALTER TABLE dbo.CHARGES ADD CONSTRAINT FK_CHARGES_CHARGE_TYPES FOREIGN KEY (charge_type_id) REFERENCES dbo.CHARGE_TYPES(charge_type_id);
ALTER TABLE dbo.CHARGES ADD CONSTRAINT FK_CHARGES_RESERVATION_ROOMS FOREIGN KEY (reservation_room_id) REFERENCES dbo.RESERVATION_ROOMS(reservation_room_id);
ALTER TABLE dbo.CHARGES ADD CONSTRAINT FK_CHARGES_RESERVATION_SERVICES FOREIGN KEY (reservation_service_id) REFERENCES dbo.RESERVATION_SERVICES(reservation_service_id);

ALTER TABLE dbo.PAYMENT_METHODS ADD CONSTRAINT UQ_PAYMENT_METHODS_name UNIQUE (payment_method_name);
ALTER TABLE dbo.PAYMENT_STATES ADD CONSTRAINT UQ_PAYMENT_STATES_name UNIQUE (payment_state_name);
ALTER TABLE dbo.PAYMENTS ADD CONSTRAINT CK_PAYMENTS_amount CHECK (amount > 0);
ALTER TABLE dbo.PAYMENTS ADD CONSTRAINT FK_PAYMENTS_RESERVATIONS FOREIGN KEY (reservation_id) REFERENCES dbo.RESERVATIONS(reservation_id);
ALTER TABLE dbo.PAYMENTS ADD CONSTRAINT FK_PAYMENTS_PAYMENT_METHODS FOREIGN KEY (payment_method_id) REFERENCES dbo.PAYMENT_METHODS(payment_method_id);
ALTER TABLE dbo.PAYMENTS ADD CONSTRAINT FK_PAYMENTS_PAYMENT_STATES FOREIGN KEY (payment_state_id) REFERENCES dbo.PAYMENT_STATES(payment_state_id);
GO
